FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Копируем uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Копируем зависимости
COPY pyproject.toml uv.lock ./

# копируем README перед sync
COPY README.md ./

# Синхронизируем окружение
RUN uv sync --frozen --no-dev

# Копируем код
COPY . .

# Запуск Celery
CMD ["uv", "run", "celery", "-A", "workers.celery_app", "worker", "--loglevel=info"]