"""Initial players and ships tables

Revision ID: 277454c7e69f
Revises: 
Create Date: 2026-06-15 16:58:58.599037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277454c7e69f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_telegram_id'), 'players', ['telegram_id'], unique=True)
    op.create_table('ships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('tea_level', sa.Float(), nullable=False),
    sa.Column('optimism', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('defense', sa.Float(), nullable=False),
    sa.Column('luck', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ships_id'), 'ships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ships_id'), table_name='ships')
    op.drop_table('ships')
    op.drop_index(op.f('ix_players_telegram_id'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
