"""Add player balances

Revision ID: 78140186e4f2
Revises: 240af1aee6cc
Create Date: 2026-06-17 11:36:56.761458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78140186e4f2'
down_revision: Union[str, Sequence[str], None] = '240af1aee6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('xgen_balance', sa.Integer(), server_default='0', nullable=False))
    op.add_column('players', sa.Column('fragments_balance', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'fragments_balance')
    op.drop_column('players', 'xgen_balance')
    # ### end Alembic commands ###
