"""Fix names guide progress tables

Revision ID: 8d0a3e2c6cc1
Revises: 04a2b630cec5
Create Date: 2026-06-18 20:01:59.954260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d0a3e2c6cc1'
down_revision: Union[str, Sequence[str], None] = '04a2b630cec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters_completion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_completion_id'), 'chapters_completion', ['id'], unique=False)
    op.create_table('articles_trigger_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_trigger_progress_id'), 'articles_trigger_progress', ['id'], unique=False)
    op.create_table('unlocked_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unlocked_articles_id'), 'unlocked_articles', ['id'], unique=False)
    op.drop_index(op.f('ix_unlocked-articles_id'), table_name='unlocked-articles')
    op.drop_table('unlocked-articles')
    op.drop_index(op.f('ix_chapters-completion_id'), table_name='chapters-completion')
    op.drop_table('chapters-completion')
    op.drop_index(op.f('ix_articles-trigger-progress_id'), table_name='articles-trigger-progress')
    op.drop_table('articles-trigger-progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles-trigger-progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('articles-trigger-progress_article_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('articles-trigger-progress_player_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('articles-trigger-progress_pkey'))
    )
    op.create_index(op.f('ix_articles-trigger-progress_id'), 'articles-trigger-progress', ['id'], unique=False)
    op.create_table('chapters-completion',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('chapters-completion_chapter_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('chapters-completion_player_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chapters-completion_pkey'))
    )
    op.create_index(op.f('ix_chapters-completion_id'), 'chapters-completion', ['id'], unique=False)
    op.create_table('unlocked-articles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('unlocked-articles_article_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('unlocked-articles_player_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('unlocked-articles_pkey'))
    )
    op.create_index(op.f('ix_unlocked-articles_id'), 'unlocked-articles', ['id'], unique=False)
    op.drop_index(op.f('ix_unlocked_articles_id'), table_name='unlocked_articles')
    op.drop_table('unlocked_articles')
    op.drop_index(op.f('ix_articles_trigger_progress_id'), table_name='articles_trigger_progress')
    op.drop_table('articles_trigger_progress')
    op.drop_index(op.f('ix_chapters_completion_id'), table_name='chapters_completion')
    op.drop_table('chapters_completion')
    # ### end Alembic commands ###
