"""Add inventory system and item requirements for articles

Revision ID: f268ddf7b58f
Revises: 8d0a3e2c6cc1
Create Date: 2026-06-24 15:55:52.667550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f268ddf7b58f'
down_revision: Union[str, Sequence[str], None] = '8d0a3e2c6cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('effect', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_tradable', sa.Boolean(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('required_item_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'articles', 'items', ['required_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'required_item_id')
    op.drop_table('inventory_items')
    op.drop_table('items')
    # ### end Alembic commands ###
